### ISSUE TITLE
osx-arm64 builds unsolvable

### ISSUE THREAD

**Issue by mfansler** [conda-forge/apache-beam-feedstock#44]
### Issue
All builds for **osx-arm64** are unsolvable because lack of `dill >=0.3.1.1,<0.3.2`. This slips under the radar due to the no testing policy for non-native builds.

### Recreate

```bash
CONDA_SUBDIR=osx-arm64 mamba create -n foo -c conda-forge apache-beam
```

**Output**
<details>

```bash

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.16.0) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['apache-beam']

pkgs/main/osx-arm64      [====================] (00m:00s) Done
bioconda/osx-arm64       [====================] (00m:00s) 404 Failed
pkgs/r/noarch            [====================] (00m:00s) No change
pkgs/r/osx-arm64         [====================] (00m:00s) 404 Failed
conda-forge/osx-arm64    [====================] (00m:00s) Done
pkgs/main/noarch         [====================] (00m:00s) Done
bioconda/noarch          [====================] (00m:00s) Done
conda-forge/noarch       [====================] (00m:01s) Done
Encountered problems while solving:
  - nothing provides dill >=0.3.1.1,<0.3.2 needed by apache-beam-2.29.0-py38hea4295b_0
```

</details>

### Recommendation
This cannot be resolved here, but I thought it should at least be tracked.

**Comment by xylar** [comment]
Thanks for reporting this.  I'm happy to take care of the dill feedstock.

**Comment by xylar** [comment]
Should be fixed as soon as https://github.com/conda-forge/dill-feedstock/pull/30 gets merged and the noarch version gets built.

**Comment by xylar** [comment]
@mfansler, can you check if this issue has been fixed and close this if so?

**Comment by mfansler** [comment]
Dill is solving fine now (thanks!), but looks like the `python-avro` constraints are also unsatisfiable.

```bash
Encountered problems while solving:
  - nothing provides python-avro >=1.8.1,!=1.9.2,<1.10.0 needed by apache-beam-2.29.0-py38hea4295b_0
```

Unfortunately, I don’t know an automatic way to check all the dependencies.

**Comment by xylar** [comment]
No worries. I don't have an osx-arm machine but I can do dry-run builds and investigate these problems. Thanks for the update.

**Comment by xylar** [comment]
I tested all of the remaining dependencies besides `python-avro` and they seem to be fine on `osx-arm64`.  I'll take care of rebuilding `python-avro` 1.8.2 for `osx-arm64`.

**Comment by xylar** [comment]
@mfansler, this should be solved in about an hour, once the packages from https://github.com/conda-forge/python-avro-feedstock/pull/25 are built.  I'll do a dry-run check but would appreciate having you try again on your end before we close this issue.

I haven't attempted to check the "extras" packages on OSX Arm yet.  Let me know if these are important for you as well.

**Comment by xylar** [comment]
It took a bit longer than expected for the package to register but the following just worked for me:
```
CONDA_SUBDIR=osx-arm64 mamba create -n test --dry-run apache-beam
```
@mfansler, let me know how it goes.

**Comment by mfansler** [comment]
Great! Seeing everything working. 👌
