### ISSUE TITLE
Regular Beam Conda Release

### ISSUE THREAD

**Issue by aaltay** [conda-forge/apache-beam-feedstock#8]
Hi,

We recently had a discussion in Beam's mailing list about this conda distribution. (Reference: https://lists.apache.org/thread.html/da913ff4b73e7efe7974ef8845da537d5fdb244cc454d377fc4e8619@%3Cdev.beam.apache.org%3E)

Thank you for doing this. We would like to understand how to better serve users using this package, ideally we can:
- incorporate this package into beam's regular release process
- add tests for testing this as part of beam's integration tests.

We would be happy to chat.

**Comment by sodre** [comment]
@aaltay,
Sorry for not seeing this post sooner!  I am more than happy to add the you guys as maintainers of the conda-package. The advantage, is that you know better than anyone, what dependencies changed between each individual release. 

To get started I would ask that one of you take a look at the [maintainer documentation](http://conda-forge.org/docs/maintainer/00_intro.html) for conda-forge, and then follow on with a PR adding the github user names of who would like to be a co-maintainer of the package. I will merge the PR and you should be able to start controlling the release of apache-beam into conda-forge.

**Comment by aaltay** [comment]
Thank you and sorry for the delay.

Sent https://github.com/conda-forge/apache-beam-feedstock/pull/12 to add myself as a co-maintainer.
