### ISSUE TITLE
Drop duplicate `conda_build` key from `conda-forge.yml`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/apache-beam-feedstock#81]
There appears to be a duplicate `conda_build` key in `conda-forge.yml`

https://github.com/conda-forge/apache-beam-feedstock/blob/e5ee9246baa80741a73639d2110034d75b599846/conda-forge.yml#L3-L4

https://github.com/conda-forge/apache-beam-feedstock/blob/e5ee9246baa80741a73639d2110034d75b599846/conda-forge.yml#L9-L10

This is causing some issues for the bot (used for version updates and migrators)

Could we drop one of these?

**Comment by xylar** [comment]
@jakirkham, happy to fix that in #78.  That particular PR is stuck waiting for https://github.com/conda-forge/pyjsparser-feedstock/pull/1.  Is that a PR you'd be willing to merge for me?  I think I've waited long enough for the maintainer(s) to respond but you can see if you agree.
